version: '3.6'
services:
  iris:
    build:
      context: .
      dockerfile: dockerfile
    restart: always
    ports:
      - 1972
      - 55038:52773
      - 53773
    volumes:
      - ./:/home/irisowner/dev
